# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY}}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PAT }}
      
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "ubuntu/Dockerfile"

      # Runs a set of commands using the runners shell
      - name: Build and push container
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          docker build -t $REGISTRY/ubuntu:$VERSION ubuntu
          docker push $REGISTRY/ubuntu:$VERSION
